apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: dotnet-build-and-push-image
spec:
  params:
    - name: csprojPath
      type: string
    - name: containerRegistry
      type: string
      default: "myfakeacr.azurecr.io"
  steps:
    - name: echo
      image: alpine
      script: |
        #!/bin/sh
        echo "Building our app, creating the image and pushing it"
    - name: simple-dotnet-publish
      image: registry.access.redhat.com/ubi8/dotnet-80
      securityContext:
        runAsUser: 0 # UBI 8 images generally run as non-root
      script: |
        #!/usr/bin/bash
        # dotnet --info
        cd $(workspaces.repository.path)

        dotnet publish $(params.csprojPath) \
        -p:PublishProfile=DefaultContainer \
        -p:ContainerBaseImage=registry.access.redhat.com/ubi8/dotnet-80-runtime:latest \
        -p:ContainerRegistry=$(params.containerRegistry)

  workspaces:
    - name: repository
