apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: dotnet-build
spec:
  workspaces:
    - name: shared
  params:
    - name: GIT_REPO
      type: string
      default: "https://github.com/juanlu-sanz/mydotnettestapp"
    - name: GIT_REVISION
      type: string
      default: "main"

  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
      workspaces:
        - name: output
          workspace: shared
    - name: build-dotnet-binary
      taskRef:
        name: dotnet-build
        kind: Task
      runAfter:
        - fetch-repository
      workspaces:
        - name: repository
          workspace: shared
